/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        base: "var(--radius)",
      },
      backgroundImage: {
        "q3-gradient-border-right": "var(--q3-gradient-border-right)",
        "q3-gradient-border-bottom": "var(--q3-gradient-border-bottom)",
        "q3-gradient-border": "var(--q3-gradient-border)",

        // Rank gradients
        "rank1-bg": "var(--rank1-bg)",
        "rank1-border": "var(--rank1-border)",
        "rank2-bg": "var(--rank2-bg)",
        "rank2-border": "var(--rank2-border)",
        "rank3-bg": "var(--rank3-bg)",
        "rank3-border": "var(--rank3-border)",
        "default-bg": "var(--default-bg)",
        "default-border": "var(--default-border)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",

        // q3 base colors
        "q3-base-red": "var(--q3-base-red)",
        "q3-base-orange": "var(--q3-base-orange)",
        "q3-base-green": "var(--q3-base-green)",
        "q3-base-yellow": "var(--q3-base-yellow)",
        "q3-base-lime": "var(--q3-base-lime)",
        "q3-base-embered": "var(--q3-base-embered)",
        "q3-base-cyan": "var(--q3-base-cyan)",
        "q3-base-sky": "var(--q3-base-sky)",
        "q3-base-blue": "var(--q3-base-blue)",
        "q3-base-indigo": "var(--q3-base-indigo)",
        "q3-base-purple": "var(--q3-base-purple)",
        "q3-base-pink": "var(--q3-base-pink)",

        // q3 neutrals
        "q3-neutral-default": "var(--q3-neutral-default)",
        "q3-neutral-light-v3": "var(--q3-neutral-light-v3)",
        "q3-neutral-light": "var(--q3-neutral-light)",
        "q3-neutral-light-v2": "var(--q3-neutral-light-v2)",

        // q3 surface
        "q3-surface-default": "var(--q3-surface-default)",
        "q3-surface-glass": "var(--q3-surface-glass)",
        "q3-surface-dim": "var(--q3-surface-dim)",
        "q3-surface-glass-light": "var(--q3-surface-glass-light)",
        "q3-surface-glass-normal": "var(--q3-surface-glass-normal)",
        "q3-surface-default_0": "var(--q3-surface-default_0)",
        "q3-surface-dim_0": "var(--q3-surface-dim_0)",
        "q3-surface-dimmer": "var(--q3-surface-dimmer)",
        "q3-surface-dimmest": "var(--q3-surface-dimmest)",

        // q3 strokes
        "q3-stroke-normal": "var(--q3-stroke-normal)",
        "q3-stroke-normal-v2": "var(--q3-stroke-normal-v2)",
        "q3-stroke-dark": "var(--q3-stroke-dark)",
        "q3-stroke-light": "var(--q3-stroke-light)",
        "q3-stroke-glass": "var(--q3-stroke-glass)",

        // q3 accent/danger/success/warning etc.
        "q3-accent-normal": "var(--q3-accent-normal)",
        "q3-accent-light": "var(--q3-accent-light)",
        "q3-accent-dark": "var(--q3-accent-dark)",
        "q3-danger-light": "var(--q3-danger-light)",
        "q3-danger-normal": "var(--q3-danger-normal)",
        "q3-danger-dark": "var(--q3-danger-dark)",
        "q3-success-light": "var(--q3-success-light)",
        "q3-success-normal": "var(--q3-success-normal)",
        "q3-success-dark": "var(--q3-success-dark)",
        "q3-warning-light": "var(--q3-warning-light)",
        "q3-warning-normal": "var(--q3-warning-normal)",
        "q3-warning-dark": "var(--q3-warning-dark)",

        // q3 color shades (pattern)
        "q3-cyan-light": "var(--q3-cyan-light)",
        "q3-cyan-normal": "var(--q3-cyan-normal)",
        "q3-cyan-dark": "var(--q3-cyan-dark)",
        "q3-orange-light": "var(--q3-orange-light)",
        "q3-orange-normal": "var(--q3-orange-normal)",
        "q3-orange-dark": "var(--q3-orange-dark)",
        "q3-amber-light": "var(--q3-amber-light)",
        "q3-amber-normal": "var(--q3-amber-normal)",
        "q3-amber-dark": "var(--q3-amber-dark)",
        "q3-yellow-light": "var(--q3-yellow-light)",
        "q3-yellow-normal": "var(--q3-yellow-normal)",
        "q3-yellow-dark": "var(--q3-yellow-dark)",
        "q3-lime-light": "var(--q3-lime-light)",
        "q3-lime-normal": "var(--q3-lime-normal)",
        "q3-lime-dark": "var(--q3-lime-dark)",
        "q3-green-light": "var(--q3-green-light)",
        "q3-green-normal": "var(--q3-green-normal)",
        "q3-green-dark": "var(--q3-green-dark)",
        "q3-emerald-light": "var(--q3-emerald-light)",
        "q3-emerald-normal": "var(--q3-emerald-normal)",
        "q3-emerald-dark": "var(--q3-emerald-dark)",
        "q3-teal-light": "var(--q3-teal-light)",
        "q3-teal-normal": "var(--q3-teal-normal)",
        "q3-teal-dark": "var(--q3-teal-dark)",
        "q3-sky-light": "var(--q3-sky-light)",
        "q3-sky-normal": "var(--q3-sky-normal)",
        "q3-sky-dark": "var(--q3-sky-dark)",
        "q3-blue-light": "var(--q3-blue-light)",
        "q3-blue-normal": "var(--q3-blue-normal)",
        "q3-blue-dark": "var(--q3-blue-dark)",
        "q3-indigo-light": "var(--q3-indigo-light)",
        "q3-indigo-normal": "var(--q3-indigo-normal)",
        "q3-indigo-dark": "var(--q3-indigo-dark)",
        "q3-violet-light": "var(--q3-violet-light)",
        "q3-violet-normal": "var(--q3-violet-normal)",
        "q3-violet-dark": "var(--q3-violet-dark)",
        "q3-purple-light": "var(--q3-purple-light)",
        "q3-purple-normal": "var(--q3-purple-normal)",
        "q3-purple-dark": "var(--q3-purple-dark)",
        "q3-fuchsia-light": "var(--q3-fuchsia-light)",
        "q3-fuchsia-normal": "var(--q3-fuchsia-normal)",
        "q3-fuchsia-dark": "var(--q3-fuchsia-dark)",
        "q3-pink-light": "var(--q3-pink-light)",
        "q3-pink-normal": "var(--q3-pink-normal)",
        "q3-pink-dark": "var(--q3-pink-dark)",
        "q3-rose-light": "var(--q3-rose-light)",
        "q3-rose-normal": "var(--q3-rose-normal)",
        "q3-rose-dark": "var(--q3-rose-dark)",

        // q3 inverted colors
        "q3-neutral-default-inverted": "var(--q3-neutral-default_inverted)",
        "q3-neutral-light-inverted": "var(--q3-neutral-light_inverted)",

        // Rank colors
        "rank1-rank-bg": "var(--rank1-rank-bg)",
        "rank1-rank-color": "var(--rank1-rank-color)",
        "rank2-rank-bg": "var(--rank2-rank-bg)",
        "rank2-rank-color": "var(--rank2-rank-color)",
        "rank3-rank-bg": "var(--rank3-rank-bg)",
        "rank3-rank-color": "var(--rank3-rank-color)",
        "default-rank-bg": "var(--default-rank-bg)",
        "default-rank-color": "var(--default-rank-color)",
      },
    },
  },
  plugins: [],
};
